typography_spectrum: 0.3762046845000938
color:
  brandStrength: 0.8302175930237379
  lightness: 0.37449456845290297
  saturation: 0.8119958391024888
  rhythmicContrast: 0.5013908853726738
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
github: true
layout_spectrum: 0.42298805365864517
author:
  name: Utkarsh Singh
  email: usingh@dronamaps.com
  url: www.dronamaps.com
name: DronaMaps
navigation:
  - name: About Us
    id: cb84403d-0ce0-4624-a6ee-591351b8f4b9
    type: content
  - name: Verticals
    id: 938403c0-d708-4db7-bce0-a20b554c2ca3
    type: content
  - name: Careers
    id: 4413c527-30ca-496d-bfd4-513464286737
    type: content
  - name: Contact Us
    id: 9c035177-7483-4579-9014-14805e920072
    type: content
  - name: Blog
    id: e333ed96-ea22-41f6-b13b-44136b8596a0
    type: content
title: DronaMaps
content: []
description: A DronaCharya Company
purpose:
  - type: contact
    url: 'mailto:info@dronamaps.com'
    label: Request Deployment
